stages:
  - test
  - package
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_COMMIT_REF_SLUG
  DOCKER_BASE_IMAGE: hub.bizweb.vn/openjdk:11.0.10-jdk-slim-datadog
  CI_JOB_REF_DEV: "dev"
  CI_JOB_REF_STAGING: "staging"
  CI_JOB_REF_PRODUCTION: "master"
  CI_JOB_ID_DEV: $CI_JOB_ID_DEV

jib package:
  stage: package
  script:
    - mvn compile
    - mvn jib:build -Dimage=$IMAGE_TAG -Djib.from.image=$DOCKER_BASE_IMAGE -Djib.container.creationTime=$CI_COMMIT_TIMESTAMP
  tags:
    - mvn
  only:
    - dev
    - staging
    - master
  environment: $CI_COMMIT_REF_NAME

deploy-to-dev:
  extends: .deploy-to-template
  before_script:
    - export _CI_JOB_TOKEN=$CI_JOB_TOKEN_DEV
    - export _CI_JOB_REF=$CI_JOB_REF_DEV
    - export _CI_JOB_ID=$CI_JOB_ID_DEV
  only:
    refs:
      - dev
    variables:
      - $CI_REGISTRY_IMAGE

deploy-to-staging:
  extends: .deploy-to-template
  environment:
    name: staging
  before_script:
    - export _CI_JOB_TOKEN=$CI_JOB_TOKEN_STAGING
    - export _CI_JOB_REF=$CI_JOB_REF_STAGING
    - export _CI_JOB_ID=$CI_JOB_ID_STAGING
  only:
    refs:
      - staging
    variables:
      - $CI_REGISTRY_IMAGE

deploy-to-production:
  extends: .deploy-to-template
  environment:
    name: production
  before_script:
    - export _CI_JOB_TOKEN=$CI_JOB_TOKEN_PROD
    - export _CI_JOB_REF=$CI_JOB_REF_PROD
    - export _CI_JOB_ID=$CI_JOB_REF_PRODUCTION
  only:
    refs:
      - master
    variables:
      - $CI_REGISTRY_IMAGE


.deploy-to-template:
  stage: deploy
  tags:
    - curl
  cache: { }
  script:
    - echo $_CI_JOB_ID
    - echo $_CI_JOB_REF
    - echo $_CI_JOB_TOKEN
    - "curl --insecure --fail -X POST -F token=$_CI_JOB_TOKEN -F ref=$_CI_JOB_REF -F \"variables[IMAGE_TAG]=$IMAGE_TAG\" https://git.dktsoft.com:2008/api/v4/projects/$_CI_JOB_ID/trigger/pipeline"
  artifacts: { }
  variables:
    GIT_STRATEGY: none
  environment:
    name: dev
  when: on_success
  only:
    refs:
      - local
    variables:
      - $CI_REGISTRY_IMAGE
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[ci-cd .*skip\]/

