
#9090
#DEFAULT_PORT: 9090
DEFAULT_PORT: 8080

server:
  port: ${PORT:${DEFAULT_PORT}}
  #  port: localhost:8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  level:
    root: 'INFO'

spring:
  application:
    name: sapo-banner
  datasource:
    url: jdbc:mysql://localhost:3306/sapo_banner
    username: root
    password: trong286
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC

sapo:
  security:
    users:
      admin: admin,admin,ROLE_ADMIN
      user: user,user,ROLE_USER
  jwt:
    secret: MjM2MTJhMDkyY2IyYzZmYThlY2E3NzcxZTQ3YWU1YTlmYTFiM2I2ZmY5MmY4MjMwZTU3N2U5MDQyMjVhMTIxMjgzNDhkNGI2YzFlYjZjYjlhOTY0MDdmYzUyM2I4MDAxYWE4Y2ZhNTg1MDI0N2E1NTA5ZWVlNTEwYmU3MWUzNDY=
    time: 86400

---

cloud:
  aws:
    credentials:
      access-key: sdafsdafdsfsdafsda
      secret-key: idsafasdafsdfsdafdsa
    region:
      static: eu-west-1
    stack:
      auto: false

application:
  bucket:
    name: sdfsdf

---


spring:
  profiles:
    active: live

sapo:
  security:
    authentication:
      jwt:
        base64-secret: TWpNMk1USmhNRGt5WTJJeVl6Wm1ZVGhsWTJFM056Y3haVFEzWVdVMVlUbG1ZVEZpTTJJMlptWTVNbVk0TWpNd1pUVTNOMlU1TURReU1qVmhNVEl4TWpnek5EaGtOR0kyWXpGbFlqWmpZamxoT1RZME1EZG1ZelV5TTJJNE1EQXhZV0U0WTJaaE5UZzFNREkwTjJFMU5UQTVaV1ZsTlRFd1ltVTNN
        token-validity-in-seconds: 86400

---

spring:
  profiles:
    active: staging

---

spring:
  profiles:
    active: dev

---
